//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CargaPagosCGP
    {
        public int IdRegistro { get; set; }
        public string IdDestino { get; set; }
        public string TitularServicio { get; set; }
        public string CuentaClienteDestino { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public string IdUsuario { get; set; }
    }
}
