//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParametrosArcCGP
    {
        public int IdRegistro { get; set; }
        public Nullable<int> CodDolares { get; set; }
        public Nullable<int> CodColones { get; set; }
        public int IdNumEnvio { get; set; }
        public int IdConsecutivo { get; set; }
        public System.DateTime FecGeneracion { get; set; }
        public int CodEntidad { get; set; }
        public string CuentaClienteOrigenDol { get; set; }
        public string CuentaClienteOrigenCol { get; set; }
        public string IdNegocio { get; set; }
        public string NomNegocio { get; set; }
        public System.DateTime FecModificacion { get; set; }
    }
}
