//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permisos
    {
        public int IdUsuario { get; set; }
        public int IdObjeto { get; set; }
        public int Visible { get; set; }
        public int Lectura { get; set; }
        public int Escritura { get; set; }
        public int Borrado { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
    }
}
